# Generated by Django 6.0.2 on 2026-02-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customapi',
            old_name='name',
            new_name='endpoint_name',
        ),
        migrations.AlterUniqueTogether(
            name='customapi',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customapi',
            name='config',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='customapi',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='customapi',
            name='exposed_fields',
        ),
        migrations.RemoveField(
            model_name='customapi',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='customapi',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customapi',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='customapi',
            name='source_type',
        ),
    ]
