# Generated by Django 6.0.2 on 2026-02-24 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integrationcredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalizeddata',
            old_name='normalized_content',
            new_name='data',
        ),
        migrations.AlterUniqueTogether(
            name='normalizeddata',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='normalizeddata',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='normalizeddata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='IntegrationCredential',
        ),
        migrations.RemoveField(
            model_name='normalizeddata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='normalizeddata',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='normalizeddata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='normalizeddata',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='normalizeddata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='normalizeddata',
            name='url',
        ),
    ]
